api:
  insecure: true
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true # needed for self-signed cert containers
providers:
  docker:
    defaultRule: Host(`{{ normalize .Name }}.home`)
    exposedByDefault: false
    network: services
  file:
    filename: /config.yml
