api:
  dashboard: true
  # insecure: true
  # debug: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  postgres:
    address: ":5432"
  mongodb:
    address: ":27017"
serversTransport:
  # needed for self-signed cert containers
  insecureSkipVerify: true
providers:
  docker:
    defaultRule: Host(`{{ normalize .Name }}.home.singhsays.com`)
    exposedByDefault: false
    network: services
  file:
    filename: /config.yml
certificatesResolvers:
  letsencrypt:
    acme:
      email: singhsays@gmail.com
      # only used for initial settings/testing, doesn't generate valid certs
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /data/acme.json
      dnsChallenge:
        provider: digitalocean
